#!/bin/bash

if ! [ $(id -u) = 0 ]; then
    echo "The script need to be run as root." >&2
    exit 1
fi

user=${SUDO_USER:-$(whoami)}
architecture="$(dpkg --print-architecture)"

TARGET_DIR="/media/$user/kali/kali-$architecture"

if [ ! -d "$TARGET_DIR" ]; then
    >&2 echo "Could not unchroot; $TARGET_DIR does not exist!"
    exit
fi

cd "$TARGET_DIR"

mount | awk '{print $3}' | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | grep "^$TARGET_DIR" | tac | sudo xargs umount
